import {StyleSheet} from 'react-native';
import {theme} from '../../../../constant/Theme';

export const step1Style = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    width: '100%',
  },
  mainTitleContainer: {
    padding: 35,
    flex: 1.3,
    justifyContent: 'center',
    gap: 8,
  },
  title1Text: {
    // fontWeight: 'light',
    fontSize: theme.XL,
    lineHeight: 48.4,
    textAlign: 'center',
    color: theme.lightPrimaryColor,
    fontFamily: theme.PoppinsLight,
  },
  title2Text: {
    fontSize: theme.XL,
    lineHeight: 48.4,
    color: theme.lightPrimaryColor,
    fontFamily: theme.PoppinsSemiBold,
  },
  descText: {
    color: theme.blackColor,
    fontSize: theme.medium,
    lineHeight: 24,
    textAlign: 'center',
    fontFamily: theme.PoppinsRegular,
  },
  bottomSheetContainer: {
    flex: 1,
    backgroundColor: theme.primaryColor,
    borderTopLeftRadius: 35,
    borderTopRightRadius: 35,
    paddingHorizontal: 30,
    paddingVertical: 25,
    gap: 25,
  },
  chipContainer: {
    width: '100%',
    alignItems: 'center',
  },
  chip: {
    width: 64,
    height: 22,
    borderRadius: 50,
    borderWidth: 1,
    borderColor: 'rgba(158, 158, 158, 0.1)',
    paddingVertical: 7,
    paddingHorizontal: 10,
    gap: 4,
    flexDirection: 'row',
    backgroundColor: 'rgba(158, 158, 158, 0.1)',
  },
  focusClip: {
    width: 8,
    height: 8,
    borderRadius: 100,
    backgroundColor: '#ffff',
  },
  clip: {
    width: 8,
    height: 8,
    borderRadius: 100,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
  },
  buttonContainer: {
    gap: 10,
  },
  facebookButton: {
    width: '100%',
    borderRadius: 50,
    height: 60,
    backgroundColor: '#4267B2',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 15,
  },
  facebookButtonText: {
    fontSize: theme.medium,
    lineHeight: 24,
    color: theme.secondaryColor,
    fontFamily: theme.PoppinsMedium,
  },
  googleButtonContainer: {
    width: '100%',
    borderRadius: 50,
    height: 60,
    backgroundColor: theme.secondaryColor,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 15,
  },
  googleButtonText: {
    fontSize: theme.medium,
    lineHeight: 24,
    color: 'rgba(0, 0, 0, 0.54)',
    fontFamily: theme.PoppinsMedium,
  },
});
