import {StyleSheet} from 'react-native';

export const step1Style = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    width: '100%',
  },
  mainTitleContainer: {
    padding: 35,
    flex: 1.3,
    justifyContent: 'center',
    gap: 8,
  },
  title1Text: {
    fontWeight: 'light',
    fontSize: 35,
    lineHeight: 48.4,
    textAlign: 'center',
    color: '#F7B174',
  },
  title2Text: {
    fontWeight: '700',
    fontSize: 35,
    lineHeight: 48.4,
    color: '#F7B174',
  },
  descText: {
    color: '#000000',
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 24,
    textAlign: 'center',
  },
  bottomSheetContainer: {
    flex: 1,
    backgroundColor: '#F7B174',
    borderTopLeftRadius: 35,
    borderTopRightRadius: 35,
    paddingHorizontal: 30,
    paddingVertical: 25,
    gap: 25,
  },
  chipContainer: {
    width: '100%',
    alignItems: 'center',
  },
  chip: {
    width: 64,
    height: 22,
    borderRadius: 50,
    borderWidth: 1,
    borderColor: 'rgba(158, 158, 158, 0.1)',
    paddingVertical: 7,
    paddingHorizontal: 10,
    gap: 4,
    flexDirection: 'row',
    backgroundColor: 'rgba(158, 158, 158, 0.1)',
  },
  focusClip: {
    width: 8,
    height: 8,
    borderRadius: 100,
    backgroundColor: '#ffff',
  },
  clip: {
    width: 8,
    height: 8,
    borderRadius: 100,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
  },
  buttonContainer: {
    gap: 10,
  },
  facebookButton: {
    width: '100%',
    borderRadius: 50,
    height: 60,
    backgroundColor: '#4267B2',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 15,
  },
  facebookButtonText: {
    fontWeight: '500',
    fontSize: 16,
    lineHeight: 24,
    color: '#ffffff',
  },
  googleButtonContainer: {
    width: '100%',
    borderRadius: 50,
    height: 60,
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 15,
  },
  googleButtonText: {
    fontWeight: '500',
    fontSize: 16,
    lineHeight: 24,
    color: 'rgba(0, 0, 0, 0.54)',
  },
});
